### ISSUE TITLE
Tree Item Arrows are invisible

### ISSUE THREAD

**Issue by schaarda** [AObuchow/Eclipse-Spectrum-Theme#123]
![image](https://user-images.githubusercontent.com/1438952/88905769-f05f0180-d256-11ea-97e2-1d1c0a76c093.png)

On Windows 7 the triangles on tree items seem to be black on black and are therefore only barely visible which makes this theme really hard to use. There was a similar error in 2015 reported against the Eclipse Dark Theme : https://bugs.eclipse.org/bugs/show_bug.cgi?id=434201
Maybe this contains hints on a solution for this theme as well.

**Comment by AObuchow** [comment]
@schaarda thank you very much for reporting & for the relevant upstream bug. I’ll work on a fix and keep you updated :)

**Comment by AObuchow** [comment]
@PyvesB hm that's problematic, as this issue might not be easily fixable/supportable in Spectrum Theme.
@schaarda does this issue also affect the standard dark theme? And what version of Eclipse IDE are you using?

**Comment by schaarda** [comment]
I'm currently using Eclipse 2020-06. At least on 2019-12 the standard dark theme did work as expected. I've not tried Standard Dark with Eclipse 2020-06 but will do so once I return (next Wednesday).

30.07.2020 19:04:59 Andrew O. <notifications@github.com>:

**Comment by AObuchow** [comment]
@schaarda thanks for the updated info, let us know how the platform dark themeI 2020-06 is when you have a moment

**Comment by schaarda** [comment]
Lesson of the day: Don't change two things at once. It seems to be a regression in Eclipse. The standard dark theme in 2020-06 has the same behavior as described above. Eclipse 2020-03 standard dark theme works as expected with visible triangles. Alas I could not try Spectrum with Eclipse 2020-03 because of unsatisfied dependencies. When I let the installer do it's problem solving magic, it simply upgrades me to 2020-06.

So this is an Eclipse bug indeed. But I doubt they're gonna fix this given the age of Win 7. So I'm going to close this bug, thanks for your help.
