### ISSUE TITLE
Incorrect tab rendering in 2020-09

### ISSUE THREAD

**Issue by PyvesB** [AObuchow/Eclipse-Spectrum-Theme#130]
Hello! 👋🏻 

When using Eclipse 2020-09, the rendering of tab folders looks odd:
![incorrect-tab-rendering](https://user-images.githubusercontent.com/10694593/91886512-b932a480-ec89-11ea-9e52-d82572c36d93.png)

As you can notice if you zoom a little, the active tab now has two top lines in red for the active tab.

The good news is that I believe that the fix is trivial and is basically reproducing this commit: https://github.com/PyvesB/eclipse-planet-themes/commit/cd9e3d404e217198a6ffad1f4ce9fdeda73de307. I reported this issue rather than submitting a pull request as I thought you may want to experiment on your own or somehow take advantage of the new behaviour in a different way. :)

**Comment by AObuchow** [comment]
@PyvesB thanks so much for bringing this up! I hadn't had a chance to check out 2020-09 yet so this is a good catch.
I'll most likely just reproduce the fix you mentioned, thanks a lot for linking me it :)
