### ISSUE TITLE
Create a preference page for the plugin

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Eclipse-Spectrum-Theme#52]
As mentioned in https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/issues/46, it'd be nice to have a preference page for this plugin.

The user could store various color schemes they've come up with and switch between them. Additionally, this would allow adding logic to calculate the theme's colors relative to the user's choice of accent/background color.

**Comment by AObuchow** [comment]
> Additionally, this would allow adding logic to calculate the theme's colors relative to the user's choice of accent/background color.

http://colormind.io/ is a cool website that lets you do something similar. 

Also worth checking out:
- https://colorhunt.co/
- https://color.adobe.com/create/color-wheel
- https://colorhunt.co/

**Comment by ingomohr** [comment]
Thanks for sharing the links, too. They could be pretty usable for any theming. :)

**Comment by AObuchow** [comment]
I think it might make sense to make the preference page in a separate feature? 
This might help organize the project structure and make it easier to reuse the theme's CSS.

**Comment by ingomohr** [comment]
> I think it might make sense to make the preference page in a separate feature?
> This might help organize the project structure and make it easier to reuse the theme's CSS.

Yes, that is true. You could also add it in its own plugin (but the same feature). That way, reusing the CSS would remain simple (from my perspective), and users don't have to wonder why they need to install 2 features.
But - just a thought.

**Comment by AObuchow** [comment]
@ingomohr awesome I wasn't aware of that, seems perfect to me :)

**Comment by AObuchow** [comment]
Fixed on the experimental branch https://github.com/AObuchow/Eclipse-Spectrum-Theme/commit/250c3f5eed96b0f8a8a8b64639f8214e65ac6cd9
