### ISSUE TITLE
Release on the Eclipse marketplace

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Eclipse-Spectrum-Theme#66]
I think it’s just about time to do the first release on the eclipse marketplace.

I believe a logo will be required, which will be for a separate issue.

**Comment by AObuchow** [comment]
Relevant links:
- https://marketplace.eclipse.org/content/eclipse-marketplace-publishing-guidelines
- https://marketplace.eclipse.org/quickstart

**Comment by AObuchow** [comment]
Here's the description I have so far:

Give Eclipse a _fresh_ new look with Spectrum Theme. This free and open-source theme plugin enhances your Eclipse IDE experience with a clean visual overhaul that can be customized to your liking.
**Plugin Features:**
- Spectrum Theme: a clean & flat visual overhaul to Eclipse IDE
- Customizable theme colors: show your style by changing the colors used in Spectrum Theme. Associate different color schemes on a per-workspace basis.
- Customizable Project Explorer font: change the size & font of the Project Explorer in Eclipse IDE

**Free and Open Source:**
Spectrum theme is an open-source project using an EPL 2.0 license. **All feedback, feature ideas, and contributions are encouraged and greatly appreciated.** The plugin is constantly improving thanks to community contributions.

**Comment by PyvesB** [comment]
Sounds great! Maybe mention "Give Eclipse 4.16+ a fresh look", the theme will blow up on older IDE versions and you'll always have some people who will try to install from the update site directly, bypassing the marketplace version check.

**Comment by AObuchow** [comment]
Great idea @PyvesB will make make sure to mention Eclipse 4.16+!

**Comment by AObuchow** [comment]
@PyvesB any idea on specifying Feature ID's for the marketplace listing? It mentions getting the feature id from the Site.xml, but I don't have one for the project's repo.

See https://marketplace.eclipse.org/quickstart (scroll down to How to specify Feature IDs)

**Comment by AObuchow** [comment]
> @PyvesB any idea on specifying Feature ID's for the marketplace listing? It mentions getting the feature id from the Site.xml, but I don't have one for the project's repo.
> 
> See https://marketplace.eclipse.org/quickstart (scroll down to How to specify Feature IDs)

I'm going to try and use `com.aobuchow.themes.spectrum.feature` as the feature id, I guess I can always modify it once the listing has been approved?

**Comment by AObuchow** [comment]
Just submitted the marketplace listing :)
![image](https://user-images.githubusercontent.com/10300119/85561030-39d58480-b5f9-11ea-89dd-61c79e3b9dad.png)

The logo looks a bit blurry since its 110x80px, maybe a low-res-optimized version should eventually be made? (If that's even possible)

**Comment by PyvesB** [comment]
> @PyvesB any idea on specifying Feature ID's for the marketplace listing? It mentions getting the feature id from the Site.xml, but I don't have one for the project's repo.
> 
> See https://marketplace.eclipse.org/quickstart (scroll down to How to specify Feature IDs)

For https://github.com/PyvesB/eclipse-solargraph I've specified `io.github.pyvesb.eclipse_solargraph` as the feature ID on the marketplace, for https://github.com/PyvesB/Notepad4e I've specified `io.github.pyvesb.notepad4e`.

I think `com.aobuchow.themes.spectrum.feature` will work in your case.

**Comment by AObuchow** [comment]
@PyvesB thanks for the info & confirmation :)

Also, in order to get marketplace to indicate that there's an update available for Spectrum Theme, is it sufficient to just have the update site's feature/plugin version to increase? Or do I have to modify the listing itself.

**Comment by PyvesB** [comment]
I _think_ it's sufficient to have the update site's feature/plugin version to increase for the embedded Marketplace client to show an update. However, I recommend updating the listing itself as well. This will make sure that the right version appears when searching for plugins and that "Date Updated" is kept up-to-date. It also puts your plugin back on top of the "New and Updated Solutions" on the marketplace, which is a good way of telling users "this has been updated, try it out if you haven't yet or give it another try if you were having issues with the previous versions".

**Comment by AObuchow** [comment]
@pyvesb thank you for that very informative reply :) 

Do you think I can just adjust the version, including the qualifier (Eg. `202006241316`) on the marketplace listing when updating the listing? This is something I'd probably do every now and then (as I might release multiple snapshot updates in a given week)

**Comment by PyvesB** [comment]
I don't use the version qualifier in the marketplace listing. Instead I use the semver one (e.g. 0.1.0). This will be more readable when displaying entries in the Marketplace client, and like that you only need to update the listing on a release, not for every single snapshot.

**Comment by ingomohr** [comment]
@AObuchow  Will the first market place release version be 0.0.1 (as it's on master)? Or do you want to make it 1.0.0 (or something else)? - W/ 0.0.1 this maybe could raise the impression to potential users that there's not much done and tested on the plugin... which would be kinda far from the truth :)

**Comment by AObuchow** [comment]
1.0.0 might suit better, although I don’t think I can edit the existing
marketplace listing until it’s approved as I’ve lost the link to it ): I
don’t know where in the marketplace website  UI to find listings waiting
for approval.

Maybe I’ll modify it once it’s approved?

**Comment by PyvesB** [comment]
Other option: 0.1.0. Some versioning schemes consider this as a beta release, whereas 0.0.1 is considered as an alpha release. You can then set the "Development Status" in the marketplace to match this. :)

**Comment by PyvesB** [comment]
The two plugins I submitted took something like 3 to 5 days to get approved if I recall correctly. I wouldn't worry too much at this stage.

**Comment by AObuchow** [comment]
Sounds good thanks letting me know @PyvesB :)

**Comment by AObuchow** [comment]
I got an email saying the listing was approved :)
[Spectrum Theme is officially on the Eclipse Marketplace :D](https://marketplace.eclipse.org/content/spectrum-dark-theme)

![image](https://user-images.githubusercontent.com/10300119/85895796-54f4ef80-b7c5-11ea-9e30-a845a3f54f8b.png)

I still intend to change the version to 1.0.0 and update the logo to be the correct resolution (might help with the blurryness) before I make an announcement on Twitter however

**Comment by PyvesB** [comment]
Nice! I've added it to my favourites! 😉

**Comment by ingomohr** [comment]
Very cool! - I also added it to my favourites :)

**Comment by AObuchow** [comment]
I just [updated](https://github.com/AObuchow/Eclipse-Spectrum-Theme/pull/94) the version to 1.0.0, will tweet about the plugin's release on Monday and close this issue finally.
