### ISSUE TITLE
Come up with a new name

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Eclipse-Spectrum-Theme#69]
Although "Modern Dark" works as a name, it might be worth coming up with a better name. On twitter, an Eclipse contributor mentioned that the word "Modern" can quickly get out-of-sync with changes in UI trends.

@pyvesb suggested naming the theme "Eclipse Spectrum Theme" which sounds nice to me. 

To quote his reasoning (in the context of the new logo ideas):
"_The dark background and the colored lines reminds me of those color spectrum charts used in physics, chemistry and astronomy. Hence my suggestion: "Eclipse Spectrum Theme". :)_"

Ideally, if the plugin is going to be renamed, it should occur before the marketplace release. I could always change the name after the 0.0.1 release, but it might confuse some users (I'm not sure how many downloads the plugin will get for the initial marketplace release, so it might not be a big deal)

All name ideas are welcome :)

**Comment by ingomohr** [comment]
I like "Spectrum" too. 👍

**Comment by AObuchow** [comment]
So I'm almost decided on using Spectrum as the new name.

However, I was thinking of calling it "Eclipse Spectrum Dark Theme" on marketplace just so people know right away that it's a dark theme. The branding & logo can just say "Spectrum Theme" or "Eclipse Spectrum Theme". 

Eventually, I'd like the theme to work both as a light/dark theme but that will probably require some upstream changes to Eclipse. Once this is done, the "dark" component from the name can be entirely removed.  

Any thoughts?

**Comment by ingomohr** [comment]
Sounds reasonable (to include "dark theme" for the marketplace).

And you could name the bundle and feature simply ``com.aobuchow.themes.spectrum``. That way, you could add light-theme support w/o having to change the ID of your bundles/feature.

**Comment by AObuchow** [comment]
Awesome thanks for all the feedback & advice @ingomohr :)

I've decided that for the plugin's marketplace release, it will be called Spectrum Theme, and the repo will be renamed to Eclipse-Spectrum-Theme. Thanks for the great suggestion @pyvesb & @cristatus !

**Comment by AObuchow** [comment]
This bug can be closed once a PR is merged to rename everything "Modern Dark" related to "Spectrum".

**Comment by AObuchow** [comment]
Currently updating the README.. here are some potentially useful emojis to spice things up hahah:


🔥🤩👀🌘🌈🔥🌑💫✨🌟🎨🌌💾📷🔮🧹📥📊🌀🔆
