### ISSUE TITLE
Code coverage colors hard to read

### ISSUE THREAD

**Issue by PyvesB** [AObuchow/Eclipse-Spectrum-Theme#79]
Hello hello!

Java code coverage colors are quite light and make the code hard to read:
<img width="387" alt="Screenshot 2020-06-23 at 15 56 21" src="https://user-images.githubusercontent.com/10694593/85412735-35ae5600-b56a-11ea-9206-9d560822d587.png">

Code coverage is provided by the [EclEmma](https://github.com/eclipse/eclemma) plugin, shipped with most default Eclipse distributions.

In the default dark theme, the colors look much better. EclEmma contributes the following styles to said Dark theme:
https://github.com/eclipse/eclemma/blob/master/org.eclipse.eclemma.ui/css/dark.css

Let me know what you think!

**Comment by AObuchow** [comment]
Thanks for reporting!

That's awesome you linked some reference CSS preferences, I'll add them soon, thank you!

**Comment by AObuchow** [comment]
I just copy/pasted eclemma's dark CSS preferences in the latest patch. Please update and let me know if it now looks better and attach a screenshot of how it looks. The colors might have to be tweaked.

**Comment by PyvesB** [comment]
Looks much better:
<img width="462" alt="Screenshot 2020-06-24 at 09 37 37" src="https://user-images.githubusercontent.com/10694593/85516385-6d66dd80-b5fe-11ea-8eff-c5b5f76988e5.png">
