### ISSUE TITLE
Marketplace icon in readme has a low resolution on HiDPI

### ISSUE THREAD

**Issue by ingomohr** [AObuchow/Eclipse-Spectrum-Theme#96]
<img width="425" alt="Screenshot 2020-06-28 at 11 34 03" src="https://user-images.githubusercontent.com/2838592/85943899-57755780-b933-11ea-8eec-7925bfc438cb.png">

The screenshot is taken on a retina display (Macbook Pro). The effect should be the same on a 4k display as well.
Compared to the other icons, the Marketplace icon has a pretty low resolution and looks a bit misplaced.

Maybe, there's a HiDPI icon for that, too? (Didn't check, though)

**Comment by AObuchow** [comment]
Thanks for pointing this out as I was unaware it was so low res. The icon was copy pasted from the “external link” section of the marketplace listing.

I’m not sure if a HiDPI version of the icon exists but maybe a bug should be made in marketplace?

**Comment by PyvesB** [comment]
I did not find any open bugs, so I opened a new one here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565317

**Comment by AObuchow** [comment]
Looks like the upstream bug has been resolved (I noticed @PyvesB 's https://github.com/PyvesB/eclipse-planet-themes/commit/1c169b69ce6bd4cbf02a6cb2244716c1352ca025 :) )

**Comment by PyvesB** [comment]
Indeed! Though I had to slightly tweak the default HTML provided by the marketplace, as width was not being properly set. 😉

**Comment by AObuchow** [comment]
@PyvesB thanks for the note ;) and thanks for reporting the upstream bug :D

**Comment by AObuchow** [comment]
@ingomohr if you're interested, feel free to take this one on btw :)

**Comment by ingomohr** [comment]
Hi there 😄  - I can't link PRs, but it's #138.

**Comment by AObuchow** [comment]
> Hi there smile - I can't link PRs, but it's #138.

Fixed via https://github.com/AObuchow/Eclipse-Spectrum-Theme/commit/d14a7471b18237330956b4f83bce86ec9d04d1ad thanks @ingomohr :D
