### ISSUE TITLE
Add GitHub shields/badges to the README

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Eclipse-Spectrum-Theme#97]
As discussed [here](https://github.com/AObuchow/Eclipse-Spectrum-Theme/pull/95#discussion_r446676367), it'd be nice to use some [badges](https://github.com/badges/shields) in the repository's README.

@pyvesb gave some really good suggestions on which we could use:

"_Yes, there are quite a few Eclipse Marketplace badges available, I recommend the downloads ones as the information is not directly available through the marketplace website. Favorites is a nice to have as well._

_GitHub commit activity is indeed another good one..._

_Another idea: you could add a badge indicating the Prettier version used by the project for example (search for "package.json dependency version" in the Shields search bar)._"

I've never added a badge to a repo before so I might need a bit of help from @pyvesb ;)

**Comment by PyvesB** [comment]
And of course you can make any decorative badge for fun:
![](https://img.shields.io/badge/Spectrum-Theme-d70000?logo=eclipse&logoColor=35ddd3)

**Comment by AObuchow** [comment]
> And of course you can make any decorative badge for fun:
> 
> ![](https://img.shields.io/badge/Spectrum-Theme-d70000?logo=eclipse&logoColor=35ddd3)

WOAH that’s so cool !!! 🤩 Would definitely be nice to use ;)

I’ll also probably need your advice on _where_ to place the badges on the README by the way :)

**Comment by PyvesB** [comment]
> I’ll also probably need your advice on _where_ to place the badges on the README by the way :)

Below the project title and horizontal line is common and would look good.

**Comment by ingomohr** [comment]
You could also add a badge showing the latest release version, the license or the build results. ^^

**Comment by ingomohr** [comment]
> You could also add a badge showing the latest release version, the license or the build results. ^^

Ah, sorry. That‘s all already in the link you‘ve added in the issue description. 😊

**Comment by AObuchow** [comment]
No worries @ingomohr, those are good ideas still :)
